### ISSUE TITLE
Atom does not install on EC2 Windows 2012R2 with Powershell 3

### ISSUE THREAD

**Issue by burtlo** [Nordstrom/chefdk_bootstrap#109]
I have been building Windows nodes and workstations for Chef Training (https://github.com/chef-training/chefdk-image/tree/master/scripts). None of it was working with Packer but that is another story.

I use the Nordstrom chefdk_bootstrap to prepare the AMI.
```
Write-Output "Execute Nordstrom ChefDK Bootstrap"
(Invoke-WebRequest -Uri https://raw.githubusercontent.com/Nordstrom/chefdk_bootstrap/master/bootstrap.ps1).Content | Invoke-Expression
```

I receive this errror. I Assume maybe all of my problems stem from having Powershell 3 installed on these EC2 instances.

<img width="873" alt="2016-03-02_14-15-10" src="https://cloud.githubusercontent.com/assets/244426/13473918/318f46c8-e081-11e5-9815-36766ad98b5e.png">

When it comes time to install Atom. It never installs and instead prompts me to open a file.

<img width="1920" alt="2016-03-02_14-15-11" src="https://cloud.githubusercontent.com/assets/244426/13474010/b2464d98-e081-11e5-948d-92decab757b4.png">

**Comment by dougireton** [comment]
@burtlo The Get-Filehash error is coming from within the ChefDK install script itself, not from our ChefDK_Bootstrap cookbook code. I think it's safe to ignore that since it seems to correctly install the ChefDK.

**Comment by dougireton** [comment]
@burtlo As to your second issue, it seems like it's getting past the Atom install and choking on the Virtualbox install.

Does AtomSetup.exe get cached in the local-mode-cache?
<img width="1312" alt="screen shot 2016-03-02 at 5 16 37 pm" src="https://cloud.githubusercontent.com/assets/30452/13481469/c2b13c74-e09a-11e5-8b99-fb479b1547c8.png">

Does Atom show up in Add/Remove Programs?

**Comment by dougireton** [comment]
Also can you run this on the EC2 instance and let me know if you get the file popup again?

```PowerShell
# run PowerShell in an elevated Admin console
cd $env:TEMP\chefdk_bootstrap
chef-client -A -z -l debug -c $env:TEMP\chefdk_bootstrap\client.rb -o chefdk_bootstrap
```

**Comment by dougireton** [comment]
@burtlo you should consider setting Virtualbox (and maybe Vagrant) install attributes to `false` via the [JSON Attributes env var](https://github.com/Nordstrom/chefdk_bootstrap#json-attributes) if you don't need them. That way the cookbook won't try to install them which will save you time.

**Comment by dougireton** [comment]
@burtlo I have reproduced this once on a Windows 2012r2 Vagrant box. Looking into this a bit deeper now.

**Comment by burtlo** [comment]
You're right I don't need VirtualBox. It successfully installs. Atom never makes it on the desktop. I will check to see if it gets in the Add/Remove programs. I have a guess that it does not.

I'll attempt running that script.
