### ISSUE TITLE
Don't install Virtualbox on VMs

### ISSUE THREAD

**Issue by dougireton** [Nordstrom/chefdk_bootstrap#114]
Detect if we are installing on a VM and skip VirtualBox install.

https://github.com/sethvargo/chef-sugar/blob/master/lib/chef/sugar/virtualization.rb

**Comment by oifland** [comment]
Related: http://stackoverflow.com/questions/39533/how-to-identify-that-youre-running-under-a-vm

**Comment by dougireton** [comment]
Even better: https://github.com/sethvargo/chef-sugar/blob/master/lib/chef/sugar/virtualization.rb

**Comment by MarkGibbons** [comment]
We should figure out why this was reported?

**Comment by dougireton** [comment]
I don't remember now, but maybe someone was running this on a VDI?

**Comment by MarkGibbons** [comment]
Fix is in #162

**Comment by MarkGibbons** [comment]
Fixed
