### ISSUE TITLE
Bootstrap script should install latest ChefDK available by default

### ISSUE THREAD

**Issue by dougireton** [Nordstrom/chefdk_bootstrap#123]
Right now we hardcode the ChefDK version like this:

```powershell
$targetChefDk = '0.12.0'
```

## Expected
Bootstrap script installs latest ChefDK version available from Chef.
Bootstrap doesn't reinstall the latest version if you already have it (idempotency).

## Actual
We have to update this manually every time ChefDK bumps which is now monthly.

**Comment by webframp** [comment]
This cookbook provides a chefdk resource: https://github.com/RoboticCheese/chef-dk-chef

It does so using the [omnijack gem](https://github.com/RoboticCheese/omnijack-ruby)

So there's two possible paths in light of this:

1. Just use `chefdk` in the metadata and rewrite the recipes to use the resource as needed
2. Integrate using the omnijack gem in a helper library or similar

see any other approach?
