### ISSUE TITLE
Remove support of custom cookbooks and private supermarkets

### ISSUE THREAD

**Issue by donneler** [Nordstrom/chefdk_bootstrap#143]
@dougireton Does it make sense to continue supporting custom cookbooks and private supermarkets? We can't really test these since we don't use this feature. Are these being used?

**Comment by oifland** [comment]
I think we should go ahead with this for v2.

**Comment by dougireton** [comment]
I'm all for simplifying. It'd be great to have a deprecation notice though.

**Comment by donneler** [comment]
Part of the 2.0.0 release
