### ISSUE TITLE
Vagrant-VirtualBox version conflict

### ISSUE THREAD

**Issue by oifland** [Nordstrom/chefdk_bootstrap#145]
Right now, we're installing Vagrant 1.8.1 (because that's the default from the vagrant cookbook), which doesn't support the latest version of VirtualBox (5.1.x), leaving users in a state that they can't use kitchen out of the box.

I've heard that an update may be coming soon to the vagrant cookbook, but if it doesn't land soon, we should add an attribute to specify the latest (1.8.5) version of Vagrant.

**Comment by dougireton** [comment]
I'm working on a PR to the Vagrant cookbook.

**Comment by dougireton** [comment]
Fixed by https://github.com/jtimberman/vagrant-cookbook/pull/65
