### ISSUE TITLE
Current version of Chocolately breaks cookbooks

### ISSUE THREAD

**Issue by ekrengel** [Nordstrom/chefdk_bootstrap#146]
Latest version (0.10.0) of Chocolately require checksums not be empty. This is a breaking change for our cookbooks as we are not currently using checksums.

**Comment by donneler** [comment]
Currently working on a work around to use empty checksums. Will need to work on a more secure solution afterwards.

**Comment by MarkGibbons** [comment]
I don't see a problem here for us.  It seems like the fix should be upstream in the chef chocolatey package resource.  Will verify that the package are installed and then close this issue.

**Comment by ekrengel** [comment]
@MarkGibbons can we close this issue or remove me as an assignee?

**Comment by MarkGibbons** [comment]
Removed you.

**Comment by MarkGibbons** [comment]
I can't reproduce this error any more.
