### ISSUE TITLE
Fix awful default PowerShell git status and prompt colors

### ISSUE THREAD

**Issue by dougireton** [Nordstrom/chefdk_bootstrap#40]
See these articles for more info:

http://sedodream.com/2012/05/05/GitCustomizingColorsForWindowsIncludingPoshgit.aspx
http://shallowsky.com/blog/programming/gitcolors.html
http://stackoverflow.com/questions/18420139/changing-git-status-output-colors-in-posh-git

**Comment by oifland** [comment]
Also, you can change the PowerShell background color:
$Host.UI.RawUI.BackgroundColor = 'black'

See https://social.technet.microsoft.com/Forums/windowsserver/en-US/4b43f071-abf5-4a65-9048-82d474473a8e/how-can-i-set-the-powershell-console-background-color-not-the-text-background-color?forum=winserverpowershell

**Comment by oifland** [comment]
It looks like setting the foreground color to white will make all the foreground fonts brighter (including red), making it more readable, and this can be accomplished with a simple `$Host.UI.RawUI.ForegroundColor = 'White'` in PowerShell.

We could change the background color to something less blue, e.g. RGB(1,29,45), but that would likely be a bit trickier and might lead to confusion with cmd.exe or ConEmu.
