### ISSUE TITLE
Append internally-managed root CA SSL certs to ChefDK CA bundle

### ISSUE THREAD

**Issue by jmccann** [Nordstrom/chefdk_bootstrap#44]
As an Enterprise Organization we have internal root CAs that we need to have added to our certificate bundle to be able to connect to our internal servers, services (dev related like supermarket, chef servers, etc. signed with our internal root CA) and proxy without SSL warnings.

It would be great if this cookbook provided an easy way to add CA certificates to the system similar to how it's easy to configure the proxy. :smile:

**Comment by dougireton** [comment]
@jmccann I completely agree. We have this exact need as well. I have been thinking about how to append a root public key to the bundled SSL certs.

I see these things coming first, based on current work in progress.
1. Complete refactor of the Vagrant and Chocolatey installs, which will also add installing "vagrant-winrm" plugin. ETA 1.5 weeks.
2. Move ~/chef directory creation to cookbook and remove from bootstrap script, plus misc cleanup work. 1 day
3. Remove misleading "Setup complete" message when bootstrap script throws an error. 1 day

**Comment by dougireton** [comment]
@jmccann do you still have this need? We no longer need this feature since we've moved to a 3rd-party cert for our git server, so that's why this bug has languished.

If having this feature would be helpful we can start looking into this. First step is probably ChefSpec tests.

Sorry this has fallen off our radar.

Doug

**Comment by irvingpop** [comment]
Hey Doug, I've had several Chef customers express interest to me in this feature.  So it's definitely something on the radar for my team.

**Comment by dougireton** [comment]
Thanks @irvingpop. We'll prioritize accordingly.

**Comment by jmccann** [comment]
@dougireton Some examples of how this would be helpful for us:

* artifact repositories that are internally signed hosting vagrant boxes for kitchen-vagrant testing
* openstack services using internally signed certs for kitchen-openstack testing
* chef servers use internally signed certs
* our supermarket uses internally signed certs

Thanks for checking in on this!

**Comment by dougireton** [comment]
@jmccann how are your users installing the internal certs now? I want to make sure we solve your problem instead of just guessing.

Do you host the CA certs on a web server and curl them down, or would you want to paste the cert as text into a cookbook attribute?

**Comment by mattstratton** [comment]
An area where this could help a lot is with users who are in enterprises with SSL-intercepting proxies like Bluecoat, where the CA for the Bluecoat needs to be added to the certstore for chefdk. This is becoming more and more of a common issue that I'm seeing out there :)

**Comment by dougireton** [comment]
@mattstratton @irvingpop @oifland Can we hop on a Zoom call for about 30min to discuss the design? We switched to external certs at Nordstrom and no longer have to deploy internal cert chains. I want to add this feature, but I need more info to get the design right.

Monday - Wednesday of next week would work for me.

**Comment by mattstratton** [comment]
@dougireton I know that @irvingpop is OOTO this week, but I would be happy to jump on a call.

I created a Doodle scheduling link for anyone who wants to join. Please fill out your choices today and I'll schedule it and post the date/time/link to this issue after.

**Comment by dougireton** [comment]
I updated the Doodle link with my available times.

**Comment by MarkGibbons** [comment]
Fixed by #161.   A CA bundle can be included in the JSON attributes file to be added to the chef cacert file.
