### ISSUE TITLE
bootstrap fails if Home Brew is already installed

### ISSUE THREAD

**Issue by paul5280** [Nordstrom/chefdk_bootstrap#45]
I get the following error:

It appears Homebrew is already installed. If your intent is to reinstall you
should do the following before running this installer again:
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"

**Comment by dougireton** [comment]
full idempotency for bootstrap script

**Comment by dougireton** [comment]
Fixed by v1.3.1
