### ISSUE TITLE
Install reasonable set of Atom packages

### ISSUE THREAD

**Issue by dougireton** [Nordstrom/chefdk_bootstrap#54]
We should install a reasonable set of Atom packages, e.g. 

├── language-powershell
├── linter
├── linter-foodcritic
├── linter-rubocop
├── merge-conflicts

The right way to do this is to write an Atom cookbook with an `atom_package` resource.

**Comment by dougireton** [comment]
First we have to refactor and update the [chef-atom cookbook](https://github.com/mohitsethi/chef-atom).

**Comment by MarkGibbons** [comment]
Fixed by #161.  See the attributes for the list of plugins installed.
