### ISSUE TITLE
Atom installation issues

### ISSUE THREAD

**Issue by ctbarrett** [Nordstrom/chefdk_bootstrap#67]
Mostly an FYI regarding an upstream issue with Atom...

I was helping a colleague get their Win7 workstation configured recently, and ran into problems with the Atom installation steps. Unfortunately I did not get copies of the logs from her sessions while we were troubleshooting, but the issue tracked back to this, upstream: https://discuss.atom.io/t/windows-7-install-issue-both-1-0-19-and-1-1-0-beta/21292/4. In her case, it was a McAfee enterprise AV client.

Not sure if there's an easy way to check for an antivirus client, or lock down the conditions to something a bit more specific than "it might not work if you have an AV client installed and active," but it's perhaps worth adding a note in the README, at least.

**Comment by dougireton** [comment]
Closing this until we have a consistent repro case. I hesitate to add things to the README when all my experience tells me that no one reads it as is.

Thanks for reporting it.
