### ISSUE TITLE
Write PowerShell profile customizations to $Profile.CurrentUserAllHosts

### ISSUE THREAD

**Issue by oifland** [Nordstrom/chefdk_bootstrap#75]
There may be other issues, but the most glaring difference is that the cookbook only puts the profile in as the PowerShell profile, which is 1 of 6 profiles (and not the one used by ISE).

We need to review how profiles are selected, how they work with ISE, and make changes to support PowerShell ISE as a first-class option for installation.

**Comment by dougireton** [comment]
http://stackoverflow.com/questions/29122839/how-to-load-profile-in-powershell-ise
