### ISSUE TITLE
Installing chefdk-julia gem creates .chefdk directory owned by root

### ISSUE THREAD

**Issue by dougireton** [Nordstrom/chefdk_bootstrap#88]
Setting the `node['chefdk_bootstrap']['package']['chefdk_julia']` attribute to `true` installs chefdk-julia in the user's `~/.chefdk` directory, but the `~/.chefdk` directory is owned by root. This causes `chef gem install` to fail when a user runs it.

```
chef gem install stove
Fetching: logify-0.2.0.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /Users/me/.chefdk/gem/ruby/2.1.0/cache/logify-0.2.0.gem
```

We need to install chefdk-julia as the user.

**Comment by dougireton** [comment]
Here's an idea:
http://stackoverflow.com/questions/23680177/installing-gem-into-chefdk-via-chef

**Comment by MarkGibbons** [comment]
The latest version of chef included in chefdk appears to install the chefdk-julia gem in an /opt/chefdk directory.  Verify with different settings for  GEM_ROOT and on a new mac install.

**Comment by MarkGibbons** [comment]
This problem doesn't happen any move.
